### ISSUE TITLE
less-rails doesn't load with Ruby 2.4.0

### ISSUE THREAD

**Issue by qingchengnus** [metaskills/less-rails#133] opened 2017-03-13 04:00 UTC
I'm getting following error when deploy Rails application with Ruby 2.4.0

Bundler::GemRequireError: There was an error while trying to load the gem 'less-rails'.
Gem Load Error is: wrong argument type Class (expected Module).
It seems to be caused by the unification of Fixnum and Bignum into Integer in Ruby 2.4.0.

**Comment by metaskills** [comment] 2017-03-13 11:49
Is there anything that we can change? Took a quick look at the gemspec and did not see anything that stood out? Maybe a stack trace would help?

**Comment by radekosmulski** [comment] 2017-03-31 12:51
It seems the stack trace didn't copy properly. Here it is again.

`/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21: warning: constant ::Fixnum is deprecated
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'less'. (Bundler::GemRequireError)
Gem Load Error is: wrong argument type Class (expected Module)
Backtrace for gem load error is:
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `include'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `block (2 levels) in <top (required)>'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `class_eval'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `block in <top (required)>'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `each'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `<top (required)>'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8.rb:22:in `require'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8.rb:22:in `<top (required)>'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:2:in `require'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:2:in `<top (required)>'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/less-2.6.0/lib/less/java_script.rb:9:in `require'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/less-2.6.0/lib/less/java_script.rb:9:in `default_context_wrapper'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/less-2.6.0/lib/less/java_script.rb:17:in `context_wrapper'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/less-2.6.0/lib/less/loader.rb:13:in `initialize'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/less-2.6.0/lib/less.rb:14:in `new'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/less-2.6.0/lib/less.rb:14:in `<module:Less>'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/less-2.6.0/lib/less.rb:9:in `<top (required)>'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:91:in `require'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `each'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `block in require'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `each'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `require'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler.rb:107:in `require'
/home/radek/workspace/radar-information-center/config/application.rb:11:in `<top (required)>'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:78:in `require'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:78:in `block in server'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `tap'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `server'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
Bundler Error Backtrace:
        from /home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
        from /home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `each'
        from /home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `block in require'
        from /home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `each'
        from /home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `require'
        from /home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.5/lib/bundler.rb:107:in `require'
        from /home/radek/workspace/radar-information-center/config/application.rb:11:in `<top (required)>'
        from /home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:78:in `require'
        from /home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        from /home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/radek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
`

**Comment by radekosmulski** [comment] 2017-03-31 12:53
Looks like it is an issue with the less gem and not less-rails...

**Comment by radekosmulski** [comment] 2017-03-31 13:00
The issue is actually with therubyracergem, upgrading to 0.12.3 solved it for me.

**Comment by brendon** [comment] 2017-05-30 10:19
@qingchengnus, does @radekosmulski's solution of upgrading the `therubyracer` gem fix your problem. If so, you should close this issue :)

**Closed** 2020-04-11 18:40 UTC
