### ISSUE TITLE
less-rails not working with Rails 6 - undefined method `pathname'

### ISSUE THREAD

**Issue by nopiece** [metaskills/less-rails#152] opened 2020-01-12 22:06 UTC
Having trouble migrating a project from Rails 5. I can reproduce with a clean Rails 6 project (Rails 6.0.2.1), using ruby 2.6.5

1. rails new -d mysql lesstest
2. edit Gemfile to remove Sass, and add less-rails and rubyracer
3. bundle install
4. generate a test controller: `rails generate controller Home index`
5. start the server, and view the page:

gem 'less-rails', '~> 4.0.0'
gem 'therubyracer'

rails server
=> Booting Puma
=> Rails 6.0.2.1 application starting in development 
=> Run `rails server --help` for more startup options
Puma starting in single mode...
* Version 4.3.1 (ruby 2.6.5-p114), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://127.0.0.1:3000
* Listening on tcp://[::1]:3000
Use Ctrl-C to stop
Started GET "/home/index" for 127.0.0.1 at 2020-01-12 15:41:32 -0600
   (1.0ms)  SET NAMES utf8mb4,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
Processing by HomeController#index as HTML
  Rendering home/index.html.erb within layouts/application
  Rendered home/index.html.erb within layouts/application (Duration: 0.6ms | Allocations: 203)
Completed 500 Internal Server Error in 49ms (ActiveRecord: 0.0ms | Allocations: 13095)

  
ActionView::Template::Error (undefined method `pathname' for #<#<Class:0x00007f99d54cec50>:0x00007f99d4685ae0>
Did you mean?  path_to_image):
     5:     <%= csrf_meta_tags %>
     6:     <%= csp_meta_tag %>
     7: 
     8:     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     9:     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    10:   </head>
    11: 
  
app/views/layouts/application.html.erb:8
`

Partial trace:
`NoMethodError in Home#index
Showing /sites/lesstest/app/views/layouts/application.html.erb where line #8 raised:

undefined method `pathname' for #<#<Class:0x00007f99d54cec50>:0x00007f99d4685ae0>
Did you mean?  path_to_image
Extracted source (around line #8):
6
7
8
9
10
11
              
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

Rails.root: /sites/lesstest

Application Trace | Framework Trace | Full Trace
less-rails (4.0.0) lib/less/rails/less_transformer.rb:41:in `config_to_less_parser_options'
less-rails (4.0.0) lib/less/rails/less_transformer.rb:19:in `evaluate'
less-rails (4.0.0) lib/less/rails/less_transformer.rb:29:in `call'
sprockets (4.0.0) lib/sprockets/processor_utils.rb:84:in `call_processor'
sprockets (4.0.0) lib/sprockets/processor_utils.rb:66:in `block in call_processors'
`

**Comment by rob-mcgrail** [comment] 2020-01-31 01:20
I've got this same error happening in rails 5.0.7

**Comment by oksromn** [comment] 2020-02-03 09:19
Same in Rails 5.1.7 (updated from 4.1.8)

```
ActionView::Template::Error (undefined method `pathname' for #<#<Class:0x00007f817f0c0a50>:0x00007f817f1846d0>
Did you mean?  path_to_image
```

**Comment by Fornacula** [comment] 2020-02-26 21:06
Same problem for me with quite  fresh setup of:
1) Rails 6.0.2.1
2) ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]

Issue is reproducable also by precompiling the assets with `bundle exec rake assets:precompile`

**Comment by jacobe** [comment] 2020-03-27 09:12
Same problem here on Rails 5.2.4.2. The full stacktrace is:
```
NoMethodError: undefined method `pathname' for #<#<Class:0x0000563ac906c520>:0x0000563ac9192e68>
Did you mean?  path_to_image
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/less-rails-4.0.0/lib/less/rails/less_transformer.rb:41:in `config_to_less_parser_options'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/less-rails-4.0.0/lib/less/rails/less_transformer.rb:19:in `evaluate'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/less-rails-4.0.0/lib/less/rails/less_transformer.rb:29:in `call'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:22:in `block in <class:CompositeProcessor>'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:33:in `call'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/loader.rb:182:in `load_from_unloaded'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/loader.rb:59:in `block in load'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/loader.rb:335:in `fetch_asset_from_dependency_cache'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/loader.rb:43:in `load'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/cached_environment.rb:44:in `load'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/bundle.rb:41:in `block in call'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/utils.rb:167:in `dfs'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/bundle.rb:42:in `call'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/loader.rb:182:in `load_from_unloaded'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/loader.rb:59:in `block in load'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/loader.rb:335:in `fetch_asset_from_dependency_cache'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/loader.rb:43:in `load'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/cached_environment.rb:44:in `load'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/base.rb:81:in `find_asset'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/base.rb:88:in `find_all_linked_assets'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:19:in `execute'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promise.rb:563:in `block in realize'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:353:in `run_task'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:342:in `block (3 levels) in create_worker'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:325:in `loop'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:325:in `block (2 levels) in create_worker'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:324:in `catch'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:324:in `block in create_worker'
```

**Comment by Jayiitb** [comment] 2020-04-11 12:08
@metaskills Please help us in fixing this issue. This is causing a lot of trouble. 🙏

**Comment by metaskills** [comment] 2020-04-11 13:51
Hey @Jayiitb thanks for asking but I really don't have the time to maintain this gem anymore and handed it off years ago. I did the same for all my SQL Server works so I an do more cloud development with Rials in the AWS eco system. 

What I can do, is offer anyone the ability to be a contributor and push to rubygems. In my absence, has there been anyone that I missed who should be added to that list?

**Comment by simi** [comment] 2020-04-11 14:16
:wave: I'm sadly not using less at all as well. But I can try to take a look at this issue. @Jayiitb could you please provide simple rails testing app reproducing this problem?

**Comment by simi** [comment] 2020-04-11 14:33
Nvm @Jayiitb I was able to reproduce this problem using steps in first post.

**Comment by simi** [comment] 2020-04-11 17:25
Can you try me new branch? Does that fix your problems?

```ruby
# in Gemfile
gem 'less-rails', git: 'https://github.com/metaskills/less-rails.git', branch: 'pathname-fix'
```

**Comment by simi** [comment] 2020-04-11 18:29
OK, I have found out the problem. You need to use sprockets 3, sprockets 4 are not supported.

For now it should be enough in your gemfile to specify:

```ruby
gem 'sprockets', '~> 3.0'
```

I'll release new major version requiring sprockets 3.0 in gemspec to help resolving on its own during application bundle.

**Comment by Jayiitb** [comment] 2020-04-11 18:36
> OK, I have found out the problem. You need to use sprockets 3, sprockets 4 are not supported.
> 
> For now it should be enough in your gemfile to specify:
> 
> ```ruby
> gem 'sprockets', '~> 3.0'
> ```
> 
> I'll release new major version requiring sprockets 3.0 in gemspec to help resolving on its own during application bundle.

@metaskills  @simi  Thanks for your apt reply.

I tried this. But without any success.

```

activesupport (5.0.7.2) lib/active_support/dependencies.rb:293:in `require'
activesupport (5.0.7.2) lib/active_support/dependencies.rb:293:in `block in require'
activesupport (5.0.7.2) lib/active_support/dependencies.rb:259:in `load_dependency'
activesupport (5.0.7.2) lib/active_support/dependencies.rb:293:in `require'
sprockets (3.7.2) lib/sprockets/autoload/sass.rb:1:in `<top (required)>'
activesupport (5.0.7.2) lib/active_support/dependencies.rb:293:in `require'
activesupport (5.0.7.2) lib/active_support/dependencies.rb:293:in `block in require'
activesupport (5.0.7.2) lib/active_support/dependencies.rb:259:in `load_dependency'
activesupport (5.0.7.2) lib/active_support/dependencies.rb:293:in `require'
sprockets (3.7.2) lib/sprockets/sass_processor.rb:47:in `initialize'
sprockets (3.7.2) lib/sprockets/sass_processor.rb:26:in `new'
sprockets (3.7.2) lib/sprockets/sass_processor.rb:26:in `instance'
sprockets (3.7.2) lib/sprockets/sass_processor.rb:30:in `call'
sprockets (3.7.2) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.7.2) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.7.2) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.7.2) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.7.2) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.7.2) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.7.2) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
sprockets (3.7.2) lib/sprockets/loader.rb:44:in `load'
sprockets (3.7.2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.7.2) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.7.2) lib/sprockets/bundle.rb:23:in `block in call'
sprockets (3.7.2) lib/sprockets/utils.rb:200:in `dfs'
sprockets (3.7.2) lib/sprockets/bundle.rb:24:in `call'
sprockets (3.7.2) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.7.2) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.7.2) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.7.2) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.7.2) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.7.2) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.7.2) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
sprockets (3.7.2) lib/sprockets/loader.rb:44:in `load'
sprockets (3.7.2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.7.2) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.7.2) lib/sprockets/base.rb:66:in `find_asset'
sprockets (3.7.2) lib/sprockets/base.rb:92:in `[]'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:355:in `find_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:347:in `find_debug_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:229:in `block in lookup_debug_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:241:in `each'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:241:in `detect'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:241:in `resolve_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:228:in `lookup_debug_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:170:in `block in stylesheet_link_tag'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:169:in `map'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:169:in `stylesheet_link_tag'
app/views/layouts/application.html.erb:7:in `_app_views_layouts_application_html_erb___4035509606905448018_49980'
actionview (5.0.7.2) lib/action_view/template.rb:159:in `block in render'
activesupport (5.0.7.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.7.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.7.2) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.7.2) lib/action_view/template.rb:354:in `instrument'
actionview (5.0.7.2) lib/action_view/template.rb:157:in `render'
actionview (5.0.7.2) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
actionview (5.0.7.2) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.0.7.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.0.7.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.0.7.2) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.0.7.2) lib/action_view/rendering.rb:104:in `_render_template'
actionpack (5.0.7.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.0.7.2) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.0.7.2) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.0.7.2) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.0.7.2) lib/abstract_controller/rendering.rb:26:in `render'
actionpack (5.0.7.2) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.0.7.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/jayprakash/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
activesupport (5.0.7.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.0.7.2) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (5.0.7.2) lib/action_controller/metal/implicit_render.rb:36:in `default_render'
actionpack (5.0.7.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
actionpack (5.0.7.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
actionpack (5.0.7.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.7.2) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.7.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.7.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.7.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.7.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.7.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.7.2) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.7.2) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.7.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.7.2) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.7.2) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.7.2) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.7.2) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:727:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/rack/browser_monitoring.rb:33:in `traced_call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
lib/middlewares/newrelic_middleware.rb:9:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.2.2) lib/rack/etag.rb:27:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.2.2) lib/rack/conditional_get.rb:27:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.2.2) lib/rack/head.rb:12:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
activerecord (5.0.7.2) lib/active_record/migration.rb:553:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.2.2) lib/rack/handler/webrick.rb:95:in `service'
/Users/jayprakash/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
/Users/jayprakash/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
/Users/jayprakash/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
This error occurred while loading the following files:
   sprockets/autoload/sass
   sass
```

**Comment by simi** [comment] 2020-04-11 18:36
New version released -> https://rubygems.org/gems/less-rails/versions/5.0.0. Please use that one. If you need sprockets 4 compatibility open we can continue at https://github.com/metaskills/less-rails/issues/135. Closing for now.

**Closed** 2020-04-11 18:36 UTC

**Comment by simi** [comment] 2020-04-11 18:38
@Jayiitb per your stacktrace

```
This error occurred while loading the following files:
   sprockets/autoload/sass
   sass
```

it doesn't look like less problem anymore. Since you have downgraded sprockets to 3, maybe you'll need to do the same for sass (or remove sass from gemfile at all if you do not use it).
