### ISSUE TITLE
Is therubyracer needed to be installed with less-rails?

### ISSUE THREAD

**Issue by xdougx** [metaskills/less-rails#130] opened 2017-01-10 13:50 UTC
Is in the gemfile, there is a way to avoid it?

**Comment by simi** [comment] 2020-04-11 18:53
less-rails doesn't require therubyracer directly, see gemspec https://github.com/metaskills/less-rails/blob/master/less-rails.gemspec

:information_source: dupe of https://github.com/metaskills/less-rails/issues/136

**Closed by simi** 2020-04-11 18:53 UTC
